/*
* ============================================================================
*  Name     : CSmartImageDocument from SmartImageDocument.h
*  Part of  : SmartImage
*  Created  : 06/05/2003 by Oleg Golosovskiy
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: http://www.sw4u.org/
* ============================================================================
*/

// INCLUDE FILES
#include "SmartImageDocument.h"
#include "SmartImageAppUi.h"

// ================= MEMBER FUNCTIONS =======================

// constructor
CSmartImageDocument::CSmartImageDocument(CEikApplication& aApp)
: CAknDocument(aApp)    
    {
    }

// destructor
CSmartImageDocument::~CSmartImageDocument()
    {
    }

// EPOC default constructor can leave.
void CSmartImageDocument::ConstructL()
    {
    }

// Two-phased constructor.
CSmartImageDocument* CSmartImageDocument::NewL(
        CEikApplication& aApp)     // CSmartImageApp reference
    {
    CSmartImageDocument* self = new (ELeave) CSmartImageDocument( aApp );
    CleanupStack::PushL( self );
    self->ConstructL();
    CleanupStack::Pop();

    return self;
    }
    
// ----------------------------------------------------
// CSmartImageDocument::CreateAppUiL()
// constructs CSmartImageAppUi
// ----------------------------------------------------
//
CEikAppUi* CSmartImageDocument::CreateAppUiL()
    {
    return new (ELeave) CSmartImageAppUi;
    }

// End of File  
