/*
* ============================================================================
*  Name     : CSmartImageViewSettings from SmartImageView.h
*  Part of  : SmartImage
*  Created  : 06/05/2003 by Oleg Golosovskiy
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: http://www.sw4u.org/
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
#include  <SmartImage.rsg>
#include  "SmartImageView.h"
#include  "SmartImageContainer.h" 

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CSmartImageViewSettings::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CSmartImageViewSettings::ConstructL()
    {
    BaseConstructL( R_SMARTIMAGE_VIEW1 );
    }

// ---------------------------------------------------------
// CSmartImageViewSettings::~CSmartImageViewSettings()
// ?implementation_description
// ---------------------------------------------------------
//
CSmartImageViewSettings::~CSmartImageViewSettings()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CSmartImageViewSettings::Id()
// ?implementation_description
// ---------------------------------------------------------
//
TUid CSmartImageViewSettings::Id() const
    {
    return KViewId;
    }

// ---------------------------------------------------------
// CSmartImageViewSettings::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CSmartImageViewSettings::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
        case EAknSoftkeyYes:
            {
				iContainer->ShowCurrentL();
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CSmartImageViewSettings::HandleClientRectChange()
// ---------------------------------------------------------
//
void CSmartImageViewSettings::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CSmartImageViewSettings::DoActivateL(...)
// ?implementation_description
// ---------------------------------------------------------
//
void CSmartImageViewSettings::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CSmartImageContainerSettings;
        iContainer->SetMopParent(this);
        iContainer->ConstructL((CSmartImageAppUi*)AppUi(),ClientRect() );
        AppUi()->AddToStackL( *this, iContainer );
        } 
   }

// ---------------------------------------------------------
// CSmartImageViewSettings::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CSmartImageViewSettings::DoDeactivate()
    {
    if ( iContainer )
        {
		iContainer->StoreSettings();
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// End of File


