/*
* ============================================================================
*  Name     : CSmartImageApp from SmartImageApp.cpp
*  Part of  : SmartImage
*  Created  : 06/05/2003 by Oleg Golosovskiy
*  Implementation notes:
*
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: http://www.sw4u.org/
* ============================================================================
*/

// INCLUDE FILES
#include    "SmartImageApp.h"
#include    "SmartImageDocument.h"

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CSmartImageApp::AppDllUid()
// Returns application UID
// ---------------------------------------------------------
//
TUid CSmartImageApp::AppDllUid() const
    {
    return KUidSmartImage;
    }

// ---------------------------------------------------------
// CDictionaryStore* CSmartImageApp::OpenIniFileLC(RFs& aFs) const
// overrides CAknApplication::OpenIniFileLC to enable INI file support
// ---------------------------------------------------------
//
CDictionaryStore* CSmartImageApp::OpenIniFileLC(RFs& aFs) const
{
    return CEikApplication::OpenIniFileLC(aFs);
}
   
// ---------------------------------------------------------
// CSmartImageApp::CreateDocumentL()
// Creates CSmartImageDocument object
// ---------------------------------------------------------
//
CApaDocument* CSmartImageApp::CreateDocumentL()
    {
    return CSmartImageDocument::NewL( *this );
    }

// ================= OTHER EXPORTED FUNCTIONS ==============
//
// ---------------------------------------------------------
// NewApplication() 
// Constructs CSmartImageApp
// Returns: created application object
// ---------------------------------------------------------
//
EXPORT_C CApaApplication* NewApplication()
    {
    return new CSmartImageApp;
    }

// ---------------------------------------------------------
// E32Dll(TDllReason) 
// Entry point function for EPOC Apps
// Returns: KErrNone: No error
// ---------------------------------------------------------
//
GLDEF_C TInt E32Dll( TDllReason )
    {
    return KErrNone;
    }

// End of File  

