/*
* ============================================================================
*  Name     : CSmartImageViewShow from SmartImageView2.h
*  Part of  : SmartImage
*  Created  : 06/05/2003 by Oleg Golosovskiy
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: http://www.sw4u.org/
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
#include  <SmartImage.rsg>
#include  "SmartImageView2.h"
#include  "SmartImageContainer2.h" 
#include  "SmartImageAppUi.h" 

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CSmartImageViewShow::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CSmartImageViewShow::ConstructL()
    {
	iLastCommand=0;
    BaseConstructL( R_SMARTIMAGE_VIEW2 );
    }

// ---------------------------------------------------------
// CSmartImageViewShow::~CSmartImageViewShow()
// ?implementation_description
// ---------------------------------------------------------
//
CSmartImageViewShow::~CSmartImageViewShow()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CSmartImageViewShow::Id()
// ?implementation_description
// ---------------------------------------------------------
//
TUid CSmartImageViewShow::Id() const
    {
    return KView2Id;
    }

// ---------------------------------------------------------
// CSmartImageViewShow::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CSmartImageViewShow::HandleCommandL(TInt aCommand)
    {   
	iLastCommand=aCommand;

    switch ( aCommand )
        {
		case EAknSoftkeyClose:
			{
				((CSmartImageAppUi*)AppUi())->Phone()->HangUpL();
			}
        default:
            {
            ((CSmartImageAppUi*)AppUi())->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CSmartImageViewShow::HandleClientRectChange()
// ---------------------------------------------------------
//
void CSmartImageViewShow::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CSmartImageViewShow::DoActivateL(...)
// ?implementation_description
// ---------------------------------------------------------
//
void CSmartImageViewShow::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CSmartImageContainerShow((CSmartImageAppUi*)AppUi());
        iContainer->SetMopParent(this);
        iContainer->ConstructL( ClientRect() );
        AppUi()->AddToStackL( *this, iContainer );
        }
   }

// ---------------------------------------------------------
// CSmartImageViewShow::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CSmartImageViewShow::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// End of File



void CSmartImageViewShow::ResetView()
{
	iLastCommand=0;
//	iContainer->Image()->SetPicture(0);
}
