/*
* ============================================================================
*  Name     : CSmartImageContainerSettings from SmartImageContainer.h
*  Part of  : SmartImage
*  Created  : 06/05/2003 by Oleg Golosovskiy
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: http://www.sw4u.org/
* ============================================================================
*/

// INCLUDE FILES
#include "SmartImageContainer.h"
#include <SmartImage.rsg>



CSmvSettingItemList::CSmvSettingItemList(TSmiSettings& aData)
	: iData(aData)
	{
	}

CAknSettingItem* CSmvSettingItemList::CreateSettingItemL(TInt aSettingId)
{
	switch (aSettingId)
		{
	case ESmvState:
		return new (ELeave) CAknEnumeratedTextPopupSettingItem(
            aSettingId, iData.iState);
	case ESmvViewDetailsFName:
		return new (ELeave) CAknEnumeratedTextPopupSettingItem(
            aSettingId, iData.iDetailFirstName);
	case ESmvViewDetailsLName:
		return new (ELeave) CAknEnumeratedTextPopupSettingItem(
            aSettingId, iData.iDetailLastName);
	case ESmvViewDetailsPhone:
		return new (ELeave) CAknEnumeratedTextPopupSettingItem(
            aSettingId, iData.iDetailPhone);
	case ESmvViewDetailsDuration:
		return new (ELeave) CAknEnumeratedTextPopupSettingItem(
            aSettingId, iData.iDetailDuration);
	case ESmvViewDetailsEmail:
		return new (ELeave) CAknEnumeratedTextPopupSettingItem(
            aSettingId, iData.iDetailEmail);
	default:
		break;
		}
	return NULL;
}

// ================= MEMBER FUNCTIONS =======================





CSmartImageContainerSettings::CSmartImageContainerSettings()
{

}

void CSmartImageContainerSettings::ConstructL(CSmartImageAppUi* aAppUi, const TRect& aRect)
{
	iAppUi = aAppUi;

    CreateWindowL();

    SetRect(aRect);
    ActivateL();

	iListBox = new (ELeave) CSmvSettingItemList(iAppUi->Settings());
    iListBox->SetMopParent(this);
    iListBox->ConstructFromResourceL(R_SMV_SETTING_ITEM_LIST);

	iListBox->LoadSettingsL();

    iListBox->SetRect(aRect);
    iListBox->ActivateL();
}


CSmartImageContainerSettings::~CSmartImageContainerSettings()
{
	delete iListBox;
}



TInt CSmartImageContainerSettings::CountComponentControls() const
{
	if (iListBox)
		return 1;
	else
		return 0;
}

CCoeControl* CSmartImageContainerSettings::ComponentControl(TInt aIndex) const
{
    switch (aIndex)
        {
        case 0:
			return iListBox;
        default:
            return (CCoeControl*)NULL;
        }
	//return (CCoeControl*)0;
}


void CSmartImageContainerSettings::Draw(const TRect& aRect) const
{
    CWindowGc& gc = SystemGc();
    gc.SetPenStyle(CGraphicsContext::ENullPen);
    gc.SetBrushColor(KRgbGray);
    gc.SetBrushStyle(CGraphicsContext::ESolidBrush);
    gc.DrawRect(aRect);
}

void CSmartImageContainerSettings::HandleControlEventL(
    CCoeControl* /*aControl*/,TCoeEvent /*aEventType*/)
    {
    // TODO: Add your control event handler code here
    }



void CSmartImageContainerSettings::SizeChanged()
{
	if (iListBox)
		iListBox->SetRect(Rect());
}


TKeyResponse CSmartImageContainerSettings::OfferKeyEventL(const TKeyEvent& aKeyEvent, TEventCode aType )
{
	if (iListBox)
		{
		if ((aKeyEvent.iCode == EKeyUpArrow) || (aKeyEvent.iCode == EKeyDownArrow) ||
			(aKeyEvent.iCode == EKeyDevice3))
			{
			// Pass joystick up, down and pressed events to the list box.
			TKeyResponse response = iListBox->OfferKeyEventL(aKeyEvent, aType);

			if ((response == EKeyWasConsumed) && (aKeyEvent.iCode == EKeyDevice3))
				{
				if (iListBox->ListBox()->CurrentItemIndex() == 0)
					{
					iListBox->StoreSettingsL();
					iListBox->LoadSettingsL();
					}
				}
			return response;
			}
		}
	return EKeyWasNotConsumed;
}




void CSmartImageContainerSettings::ShowCurrentL()
{
	iListBox->EditItemL(iListBox->ListBox()->CurrentItemIndex(),EFalse);
}

void CSmartImageContainerSettings::StoreSettings()
{
	iListBox->StoreSettingsL();
}
