-microedition
-overloadaggressively
-repackageclasses ''
-allowaccessmodification
-keep public class * extends javax.microedition.midlet.MIDlet
-keep class ru.coldcore.Wma
-keep class ru.coldcore.Smsn
-keep class ru.coldcore.Smn
-keep class ru.coldcore.Mpq
