-libraryjars C:\WTK22\lib\midpapi20.jar;C:\WTK22\lib\wma11.jar;C:\WTK22\lib\cldcapi10.jar
-injars C:\WTK22\apps\PrivateSafe\bin\PrivateSafe.jar
-outjar C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\PrivateSafe.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
